### ISSUE TITLE
Is it suitable for other datasets?

### ISSUE THREAD

**Issue by Ruye-aa** [CGuangyan-BIT/DIT#2]
Thanks for your great work！It is an inspiring paper. 
But it is not experimented on the registration dataset 3DMatch/3DLoMatch.

I noticed that there is no downsampling process in the feature extraction stage，I wonder if DIT  is not suitable for registration tasks with low overlap rate because of this problem.

**Comment by CGuangyan-BIT** [comment]
Actually, due to the computational complexity of the Transformer (mentioned in the limitation of the paper), with the increase of the number of points, the time and memory increase significantly, which is difficult to support us to train the 3DMatch dataset on one GPU. In addition, DIT is mainly to discuss the feasibility of the full transformer structure in the field of point cloud registration, and then we will start to solve the problem of computational complexity.

**Comment by Ruye-aa** [comment]
If a downsampling process (such as the commonly used KPConv) is used at the beginning, can the complexity be reduced ？ At the same time, will reducing the number of points affect the result to a certain extent?
Thank you very much for your reply.

**Comment by CGuangyan-BIT** [comment]
The introduction of downsampling will reduce the complexity, furthermore, the efficient Transformer can further reduce the complexity.
